-- ============================================================
-- Frenchie Trivia — Complete Question Bank (500 Questions)
-- All facts verified from: AKC, FBDCA, FCI, PetMD, Wikipedia,
-- veterinary institutions, breed registries
-- ============================================================

-- Clear existing questions and reset
DELETE FROM questions;

-- Update version
UPDATE question_versions SET version_hash = 'v2.0.0-500q', updated_at = datetime('now') WHERE id = 1;

-- ============================================================
-- CATEGORY 1: BREED HISTORY (40 questions)
-- ============================================================

INSERT INTO questions (category, difficulty, question, correct_answer, incorrect_answer_1, incorrect_answer_2, incorrect_answer_3, explanation, fun_fact, is_premium, is_active) VALUES

-- Easy
('breed_history', 'easy', 'What country did French Bulldogs originally come from?', 'England', 'France', 'Germany', 'Belgium', 'Despite their name, French Bulldogs descended from English Bulldogs. Lace workers from Nottingham brought toy bulldogs to France during the Industrial Revolution.', 'The breed was produced in England, popularised in France, and perfected in America.', 0, 1),
('breed_history', 'easy', 'What year did the AKC officially recognise the French Bulldog?', '1898', '1910', '1885', '1925', 'The American Kennel Club recognised French Bulldogs in 1898 after the breed club was formed.', 'The French Bull Dog Club of America was actually formed in 1897, a year before AKC recognition.', 0, 1),
('breed_history', 'easy', 'What activity were English Bulldogs originally bred for before bull-baiting was banned?', 'Bull-baiting', 'Herding sheep', 'Hunting foxes', 'Guarding castles', 'Bulldogs were bred for bull-baiting, which involved grabbing a bull by the nose. The practice was banned in England in 1835.', 'After bull-baiting was banned in the 1830s, breeders began developing bulldogs as companion dogs instead.', 0, 1),
('breed_history', 'easy', 'What were the miniature bulldogs that became French Bulldogs originally called?', 'Toy Bulldogs', 'Mini Bulldogs', 'Pocket Bulldogs', 'Dwarf Bulldogs', 'Before becoming French Bulldogs, the breed was known as English Toy Bulldogs, weighing around 12-25 pounds.', NULL, 0, 1),
('breed_history', 'easy', 'In which century did the French Bulldog breed develop?', '19th century (1800s)', '18th century (1700s)', '20th century (1900s)', '17th century (1600s)', 'The French Bulldog developed throughout the 1800s from English Toy Bulldogs brought to France.', NULL, 0, 1),
('breed_history', 'easy', 'What was the French name given to the breed when it became popular in Paris?', 'Bouledogue Français', 'Chien Français', 'Petit Bouledogue', 'Dogue de Paris', 'The breed was named Bouledogue Français, combining "boule" (ball) and "dogue" (mastiff).', NULL, 0, 1),

-- Medium
('breed_history', 'medium', 'Which group of workers brought the ancestors of French Bulldogs to France?', 'Lace makers from Nottingham', 'Coal miners from Wales', 'Fishermen from Brittany', 'Farmers from Normandy', 'Displaced lace makers from Nottingham, England, emigrated to France during the Industrial Revolution and brought their toy bulldogs with them.', 'The lace makers settled primarily in the Normandy area of northern France.', 0, 1),
('breed_history', 'medium', 'A French Bulldog was famously aboard which doomed ship in 1912?', 'RMS Titanic', 'RMS Lusitania', 'SS Eastland', 'HMS Birkenhead', 'A French Bulldog named Gamin de Pycombe was aboard the Titanic. The dog was insured for 150 British pounds.', 'The dog''s owner, banker Robert Williams Daniel, survived the sinking. The dog did not.', 0, 1),
('breed_history', 'medium', 'What was the big ear controversy between American and English breeders about?', 'Bat ears vs rose ears', 'Cropped ears vs natural ears', 'Large ears vs small ears', 'Pointed ears vs rounded ears', 'American fanciers preferred erect "bat ears" while English breeders favoured "rose ears" that fold back like the English Bulldog.', 'Americans were so passionate about bat ears they created the first breed club to standardise them.', 0, 1),
('breed_history', 'medium', 'What was the name of the first breed club dedicated to French Bulldogs?', 'French Bull Dog Club of America', 'The French Bulldog Society of England', 'Kennel Club of France', 'International Bouledogue Club', 'The French Bull Dog Club of America, formed in 1897, was the first club in the world dedicated exclusively to the breed.', 'It was also the first breed-specific club anywhere in the world to hold a specialty show.', 0, 1),
('breed_history', 'medium', 'Where was the famous first French Bulldog specialty show held in 1898?', 'The Waldorf-Astoria hotel in New York', 'Madison Square Garden', 'The Crystal Palace in London', 'The Paris Opera House', 'After a judging controversy at Westminster where rose-eared dogs won, American fanciers organised their own show at the Waldorf-Astoria.', NULL, 0, 1),
('breed_history', 'medium', 'Which famous wealthy American families owned French Bulldogs in the early 1900s?', 'The Rockefellers and the J.P. Morgans', 'The Vanderbilts and the Carnegies', 'The Astors and the Roosevelts', 'The Hearsts and the Fords', 'French Bulldogs were status symbols among America''s elite, with dogs changing hands for up to $3,000 in the early 20th century.', 'By 1906, the French Bulldog was already the fifth most popular breed in America.', 0, 1),
('breed_history', 'medium', 'What year were French Bulldogs first exhibited at the Westminster Kennel Club Dog Show?', '1896', '1910', '1885', '1920', 'Society ladies first exhibited Frenchies at Westminster in 1896, and a Frenchie appeared on the 1897 Westminster catalogue cover.', NULL, 0, 1),
('breed_history', 'medium', 'What social groups in Paris were particularly associated with French Bulldogs in the late 1800s?', 'Parisian prostitutes and artists', 'Military officers and politicians', 'Clergy and monks', 'Factory workers and tradesmen', 'Frenchies became popular with bohemian culture in Paris, including artists and the ladies of Montmartre. Artists like Toulouse-Lautrec featured them in paintings.', NULL, 0, 1),
('breed_history', 'medium', 'When was bull-baiting officially banned in England?', '1835', '1800', '1850', '1875', 'Bull-baiting and other forms of animal combat were banned in England in 1835, which redirected Bulldog breeding toward companionship.', NULL, 0, 1),
('breed_history', 'medium', 'What breed may have been crossed with toy bulldogs in France to develop the French Bulldog?', 'Local terriers and possibly pugs', 'Poodles and spaniels', 'Dachshunds and beagles', 'Greyhounds and whippets', 'In France, the toy bulldogs were likely crossed with terriers and possibly pugs, which contributed to features like the erect bat ears.', NULL, 0, 1),
('breed_history', 'medium', 'By 1940, approximately how many French Bulldogs were registered with the AKC?', 'About 100', 'About 1,000', 'About 5,000', 'About 10,000', 'By 1940, French Bulldogs were considered a rare breed with only about 100 AKC registrations, down from peak popularity in the early 1900s.', 'Twenty years later in 1960, registrations had only climbed to 106.', 0, 1),
('breed_history', 'medium', 'What factor contributed to the decline in French Bulldog popularity after World War I?', 'The rise of the Boston Terrier', 'A ban on the breed', 'The Great Depression only', 'A disease outbreak', 'The popularity of the Boston Terrier, another small brachycephalic breed, contributed to the Frenchie''s decline. Natural whelping difficulties and heat sensitivity also played a role.', NULL, 0, 1),
('breed_history', 'medium', 'In which decade did French Bulldog registrations begin their modern surge in popularity?', '1980s', '1960s', '1970s', '1990s', 'The 1980s saw a rapid rise in Frenchie registrations, driven by newly energised breeders and the breed club.', 'By 1990, there were 632 registered French Bulldogs, up from just 106 in 1960.', 0, 1),

-- Hard
('breed_history', 'hard', 'Which famous artist painted French Bulldogs in late 19th century Paris?', 'Henri de Toulouse-Lautrec', 'Claude Monet', 'Pierre-Auguste Renoir', 'Paul Cézanne', 'Toulouse-Lautrec featured French Bulldogs in his paintings of Montmartre life. Edgar Degas is also believed to have included them.', NULL, 0, 1),
('breed_history', 'hard', 'How much was the French Bulldog on the Titanic insured for in 1912?', '150 British pounds (about $17,000 today)', '50 British pounds', '500 British pounds', '1,000 British pounds', 'Gamin de Pycombe was insured for 150 British pounds, equivalent to roughly $17,000 in today''s U.S. dollars.', NULL, 0, 1),
('breed_history', 'hard', 'In what year did the Kennel Club (UK) first recognise French Bulldogs as separate from English Bulldogs?', '1905', '1898', '1912', '1920', 'The Kennel Club changed its policy in 1905 and recognised them separately, initially as "Bouledogue Français," then as "French Bulldog" in 1912.', NULL, 0, 1),
('breed_history', 'hard', 'What ranking did French Bulldogs hold in AKC registrations in 2003?', '54th', '10th', '25th', '100th', 'In 2003, the French Bulldog was ranked 54th. By 2013, it had risen to 10th, and by 2022 it reached number 1.', NULL, 0, 1),
('breed_history', 'hard', 'Which Detroit breeder''s cream French Bulldogs won over 500 group wins and 111 Best in Show awards?', 'Amanda West', 'Elizabeth Johnson', 'Margaret Davis', 'Patricia Brown', 'Amanda West''s cream and fawn Frenchies tallied over 500 group wins, 111 Best in Show awards, and 21 consecutive breed wins at Westminster.', NULL, 0, 1),
('breed_history', 'hard', 'What year was the first American-based French Bulldog breeding program established?', '1885', '1897', '1870', '1900', 'Americans had been importing French Bulldogs, but the first formal breeding program was established in 1885.', NULL, 0, 1),
('breed_history', 'hard', 'What were the original breed standard colours when the French Bulldog was first standardised in 1897?', 'Brindle only', 'All colours', 'Fawn and cream only', 'Black and white only', 'When the standard was first created in 1897, only brindle was accepted. The standard was amended in 1911 to include fawn, cream, and piebald.', NULL, 0, 1),
('breed_history', 'hard', 'In France, what did "Bouledogue" literally mean?', 'Ball-mastiff (boule + dogue)', 'Small dog', 'Flat face', 'Short tail', 'The French name "Bouledogue Français" is a contraction of "boule" meaning ball and "dogue" meaning mastiff.', NULL, 0, 1),
('breed_history', 'hard', 'What was the French Bulldog''s AKC popularity ranking in 2013?', '10th', '1st', '25th', '50th', 'By 2013, the French Bulldog had climbed to 10th place, up from 54th just a decade earlier. The rise continued until reaching #1 in 2022.', NULL, 0, 1),
('breed_history', 'hard', 'How many French Bulldogs were registered with the AKC in 2006?', 'Over 5,500', 'About 500', 'About 1,000', 'Over 20,000', 'AKC registrations grew from 632 in 1990 to over 5,500 in 2006, marking the beginning of the breed''s explosive modern popularity.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 2: HEALTH & WELLNESS (40 questions)
-- ============================================================

('health_wellness', 'easy', 'What does BOAS stand for in relation to French Bulldog health?', 'Brachycephalic Obstructive Airway Syndrome', 'Breathing Obstruction and Airway Stenosis', 'Bulldog Obstructive Asthma Syndrome', 'Broad Airway Occlusion Syndrome', 'BOAS is caused by the flat-faced anatomy of brachycephalic breeds and can cause snoring, exercise intolerance, and breathing difficulty.', NULL, 0, 1),
('health_wellness', 'easy', 'Why can''t most French Bulldogs swim well?', 'Their heavy front body and short legs make them top-heavy', 'They are afraid of water', 'Their fur absorbs too much water', 'They have no webbing between their toes', 'Frenchies are top-heavy with a large head and chest relative to their hindquarters, making it very difficult to stay buoyant.', 'You should always put a life vest on a Frenchie near water.', 0, 1),
('health_wellness', 'easy', 'What is the average lifespan of a French Bulldog?', '10 to 12 years', '5 to 7 years', '15 to 18 years', '8 to 9 years', 'French Bulldogs typically live 10-12 years with proper care.', NULL, 0, 1),
('health_wellness', 'easy', 'Why are French Bulldogs at higher risk of heatstroke than most breeds?', 'Their flat faces make panting less efficient for cooling', 'They have thicker fur than most breeds', 'They drink less water', 'They produce more body heat', 'Dogs cool down by panting, which evaporates moisture from their airways. Brachycephalic breeds can''t pant as effectively.', 'Frenchies are twice as likely to suffer heatstroke compared to non-brachycephalic breeds.', 0, 1),
('health_wellness', 'easy', 'What common eye condition causes a red, swollen mass in the corner of a Frenchie''s eye?', 'Cherry eye', 'Glaucoma', 'Cataracts', 'Conjunctivitis', 'Cherry eye occurs when the gland of the third eyelid prolapses and becomes visible as a red, cherry-like mass.', 'Cherry eye usually requires surgery to reposition the prolapsed gland.', 0, 1),
('health_wellness', 'easy', 'What should you always use when a French Bulldog is near water?', 'A life vest', 'Water wings', 'A swimming instructor', 'Floaties', 'Due to their top-heavy build, Frenchies should always wear a canine life vest when near water.', NULL, 0, 1),
('health_wellness', 'easy', 'Why do French Bulldogs snore so loudly?', 'Their flat faces and narrow airways restrict airflow', 'They sleep more deeply than other breeds', 'They have unusually large tongues', 'They dream more than other breeds', 'The shortened airways of brachycephalic breeds create turbulent airflow, resulting in characteristic loud snoring.', NULL, 0, 1),

('health_wellness', 'medium', 'What percentage of French Bulldog litters are delivered via C-section?', 'Over 80%', 'About 50%', 'About 30%', 'Less than 10%', 'Due to the puppies'' large heads relative to the mother''s narrow pelvis, the vast majority of Frenchie births require surgical intervention.', NULL, 0, 1),
('health_wellness', 'medium', 'What spinal condition are French Bulldogs prone to due to their chondrodystrophic body type?', 'Intervertebral Disc Disease (IVDD)', 'Degenerative Myelopathy', 'Wobbler Syndrome', 'Spondylosis', 'IVDD causes discs between vertebrae to degenerate, bulge, and sometimes rupture, causing pain and potentially paralysis.', 'IVDD often strikes after age 2-3 in French Bulldogs.', 0, 1),
('health_wellness', 'medium', 'What anatomical feature called "stenotic nares" is common in French Bulldogs?', 'Abnormally narrow nostrils', 'Oversized ear canals', 'Elongated soft palate only', 'Enlarged tonsils', 'Stenotic nares are pinched or narrow nostrils that restrict airflow. Surgery to widen them can greatly improve breathing.', NULL, 0, 1),
('health_wellness', 'medium', 'What condition causes the kneecap to slip out of its normal groove in French Bulldogs?', 'Patellar luxation', 'ACL tear', 'Hip dysplasia', 'Osteochondritis dissecans', 'Patellar luxation is common in small breeds including Frenchies. You might see a Frenchie suddenly limp for a few steps then walk normally.', NULL, 0, 1),
('health_wellness', 'medium', 'What vertebral condition involves malformed, wedge-shaped bones in the spine?', 'Hemivertebrae', 'Scoliosis', 'Spina bifida', 'Lordosis', 'Hemivertebrae are malformed vertebrae that can compress the spinal cord. They are relatively common in screw-tailed breeds like Frenchies.', NULL, 0, 1),
('health_wellness', 'medium', 'What are the three main anatomical components of BOAS?', 'Elongated soft palate, stenotic nares, and narrow trachea', 'Large tongue, small lungs, and narrow ribcage', 'Short neck, flat face, and small nostrils only', 'Wide throat, small lungs, and narrow airways', 'BOAS involves an elongated soft palate, narrowed nostrils (stenotic nares), and a hypoplastic (undersized) trachea working together to obstruct airflow.', NULL, 0, 1),
('health_wellness', 'medium', 'Why are French Bulldogs more sensitive to anaesthesia than many other breeds?', 'Their compromised airways make breathing under sedation riskier', 'They metabolise drugs faster', 'They have smaller hearts', 'They are more allergic to medications', 'Brachycephalic breeds have higher anaesthesia risks due to their already compromised airways, requiring extra monitoring.', NULL, 0, 1),
('health_wellness', 'medium', 'What skin condition is caused by moisture and bacteria trapped in French Bulldogs'' facial wrinkles?', 'Skin fold dermatitis', 'Mange', 'Ringworm', 'Eczema', 'The facial folds of Frenchies can trap moisture and bacteria, leading to irritation, yeast infections, and dermatitis if not kept clean and dry.', NULL, 0, 1),
('health_wellness', 'medium', 'What type of allergies are French Bulldogs especially prone to?', 'Both food and environmental allergies', 'Only food allergies', 'Only seasonal allergies', 'Only contact allergies', 'Frenchies are prone to food allergies (especially beef, dairy, chicken) and environmental allergies (pollen, dust mites, mould).', NULL, 0, 1),
('health_wellness', 'medium', 'Why should French Bulldogs avoid jumping on and off furniture?', 'It puts stress on their spine and increases IVDD risk', 'It damages their paw pads', 'It hurts their ears', 'It makes them dizzy', 'Due to their short legs and long backs, jumping puts significant stress on the spine and can trigger or worsen IVDD.', 'Using ramps or pet stairs can help prevent spinal injuries.', 0, 1),
('health_wellness', 'medium', 'What hereditary joint condition causes the hip socket to develop abnormally?', 'Hip dysplasia', 'Patellar luxation', 'Elbow dysplasia', 'Legg-Calve-Perthes', 'Hip dysplasia is a genetic condition where the hip joint doesn''t develop properly, leading to arthritis and pain.', NULL, 0, 1),

('health_wellness', 'hard', 'What does "tracheal hypoplasia" mean in French Bulldogs?', 'An abnormally narrow windpipe from birth', 'A collapsed trachea', 'An inflamed windpipe', 'A trachea that grows too long', 'Tracheal hypoplasia means the trachea is smaller in diameter than normal, which further restricts airflow in an already compromised brachycephalic airway.', NULL, 0, 1),
('health_wellness', 'hard', 'What CHIC health tests does the FBDCA recommend for breeding French Bulldogs?', 'Hip, patella, eyes, cardiac, and BOAS evaluation', 'Only DNA panel testing', 'Only hip X-rays', 'Blood work and urinalysis only', 'The Canine Health Information Center (CHIC) list includes evaluations for hip dysplasia, patellar luxation, eye disease, cardiac issues, and BOAS.', NULL, 0, 1),
('health_wellness', 'hard', 'What eye condition causes the cornea to become cloudy and is hereditary in French Bulldogs?', 'Corneal dystrophy', 'Cherry eye', 'Cataracts', 'Progressive retinal atrophy', 'Corneal dystrophy causes the outer surface of the eye to become opaque. While not usually painful, it increases susceptibility to corneal ulcers.', NULL, 0, 1),
('health_wellness', 'hard', 'What is retinal dysplasia in French Bulldogs?', 'Abnormal formation of the retina causing vision issues', 'A swollen retina from infection', 'Detachment of the retina', 'Scarring on the retina', 'Retinal dysplasia is inherited and causes abnormal retina formation. Severe cases can cause significant vision loss or blindness, and there is no treatment.', NULL, 0, 1),
('health_wellness', 'hard', 'Why is breeding two merle French Bulldogs together considered dangerous?', 'It can cause deafness, blindness, and other severe birth defects', 'It produces all-white puppies that are harder to sell', 'It results in puppies that are too large', 'It causes coat colour that is not AKC standard', 'Double merle (homozygous merle) puppies have a significantly higher risk of serious health problems including hearing and vision defects.', NULL, 0, 1),
('health_wellness', 'hard', 'What gastrointestinal condition can cause a Frenchie to regurgitate food due to a stomach hernia?', 'Hiatal hernia', 'Bloat (GDV)', 'Pyloric stenosis', 'Megaesophagus', 'Hiatal hernias occur when part of the stomach pushes through the diaphragm, causing regurgitation. They are more common in brachycephalic breeds.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 3: GENETICS & COLOURS (38 questions)
-- ============================================================

('genetics_colours', 'easy', 'What are the AKC standard-accepted French Bulldog coat colours?', 'Fawn, brindle, white, cream, and combinations of these', 'Any colour including blue and merle', 'Only fawn and white', 'Black, brown, and white', 'The AKC breed standard accepts all brindle, fawn, white, brindle and white, and any combination except disqualifying colours.', 'The original 1897 standard only accepted brindle. Fawn, cream, and piebald were added in 1911.', 0, 1),
('genetics_colours', 'easy', 'What term describes a French Bulldog with a mostly white coat with coloured patches?', 'Pied (piebald)', 'Merle', 'Tuxedo', 'Spotted', 'Pied Frenchies have a predominantly white coat with patches of another colour, typically brindle or fawn.', NULL, 0, 1),
('genetics_colours', 'easy', 'What pattern gives French Bulldogs a "tiger stripe" appearance?', 'Brindle', 'Merle', 'Sable', 'Ticked', 'Brindle creates a pattern of dark stripes on a fawn background, ranging from sparse stripes to heavy concentration that appears almost black.', NULL, 0, 1),
('genetics_colours', 'easy', 'Is the blue (grey) coat colour accepted by the AKC for French Bulldogs?', 'No, it is a disqualifying colour', 'Yes, it is standard', 'Yes, but only for females', 'Only in combination with white', 'The AKC standard lists "mouse" (blue/grey) as a disqualifying colour. Blue Frenchies cannot compete in conformation shows.', NULL, 0, 1),
('genetics_colours', 'easy', 'What is the most common French Bulldog coat pattern?', 'Brindle', 'Solid fawn', 'Pied', 'Cream', 'Brindle is one of the most common colours/patterns seen in French Bulldogs.', NULL, 0, 1),

('genetics_colours', 'medium', 'What two genes must both be homozygous recessive to produce a lilac French Bulldog?', 'Blue dilution (d/d) and chocolate (b/b)', 'Blue dilution (d/d) and cream (e/e)', 'Chocolate (b/b) and brindle (Kbr)', 'Cream (e/e) and fawn (Ay)', 'Lilac requires both copies of the dilution gene (d/d) and both copies of the chocolate gene (b/b), creating a distinctive pale purple-grey colour.', NULL, 0, 1),
('genetics_colours', 'medium', 'What genetic locus controls the brindle pattern in French Bulldogs?', 'K locus (dominant black/brindle)', 'A locus (agouti)', 'D locus (dilution)', 'E locus (extension)', 'The K locus controls brindle expression. The Kbr allele produces the brindle striping pattern over the base colour.', NULL, 0, 1),
('genetics_colours', 'medium', 'What causes the "cream" colour in French Bulldogs?', 'Two copies of the recessive e allele (e/e) at the E locus', 'A dilution of black pigment', 'Two copies of the white gene', 'A mixture of fawn and white genes', 'Cream is caused by the homozygous recessive e/e genotype at the E locus, which prevents the production of dark (eumelanin) pigment in the coat.', 'The cream gene also masks (deletes) any black mask the dog might carry.', 0, 1),
('genetics_colours', 'medium', 'What is the AKC term for the blue/grey colour in French Bulldogs?', 'Mouse', 'Slate', 'Silver', 'Steel', 'The AKC standard uses the term "mouse" to describe the blue-grey colour produced by the dilution gene. It is a disqualifying colour.', NULL, 0, 1),
('genetics_colours', 'medium', 'What creates the melanistic mask (black face mask) on fawn French Bulldogs?', 'The Em allele at the E locus', 'The A locus agouti gene', 'The K locus brindle gene', 'The D locus dilution gene', 'The melanistic mask is controlled by the Em allele at the E locus. Only one copy is needed for the mask to appear.', 'The cream gene (e/e) will erase the mask if the dog carries two copies.', 0, 1),
('genetics_colours', 'medium', 'What is a "reverse brindle" French Bulldog?', 'A brindle where fawn stripes predominate on a dark background', 'A brindle that runs backwards', 'A brindle without any stripes', 'A brindle that changes colour seasonally', 'Light or "tiger" brindle where the lighter fawn colour is more visible is sometimes called reverse brindle. It is generally more rare.', NULL, 0, 1),
('genetics_colours', 'medium', 'What makes a "sable" French Bulldog different from a standard fawn?', 'Sable Frenchies have darker to black-tipped hairs overlaying a fawn base', 'Sable Frenchies have spots instead of solid colour', 'Sable is just another name for dark fawn', 'Sable Frenchies have curly fur', 'Sable occurs when a Fawn Frenchie has a thin layer of darker to black-tipped hairs on top of the fawn coat, controlled by the Ay/At combination at the A locus.', NULL, 0, 1),
('genetics_colours', 'medium', 'What is "ticking" in French Bulldog coat patterns?', 'Small flecked spots on white areas of the coat', 'Large patches of colour', 'Stripes on the legs only', 'Colour that changes with age', 'Ticking refers to small freckle-like spots on the white portions of a pied coat. It is accepted by the AKC but not desired.', NULL, 0, 1),
('genetics_colours', 'medium', 'What colours are listed as disqualifications in the AKC French Bulldog standard?', 'Solid black, mouse, liver, black and tan, black and white, white with black', 'Only blue and merle', 'Only black and liver', 'All non-fawn colours', 'The standard specifically disqualifies solid black, mouse (blue), liver, black and tan, black and white, and white with black.', NULL, 0, 1),
('genetics_colours', 'medium', 'What is the difference between a "black" and a "black brindle" French Bulldog?', 'Black brindle has a trace of brindle pattern; solid black has no brindle at all', 'There is no difference', 'Black brindle is lighter', 'Black is accepted and black brindle is not', 'The AKC specifies "black means black without a trace of brindle." A dark dog with even minimal brindle striping is a black brindle, which is acceptable. Solid black is a disqualification.', NULL, 0, 1),
('genetics_colours', 'medium', 'What genetic locus is responsible for the piebald (pied) pattern?', 'S locus (spotting gene)', 'K locus', 'A locus', 'M locus', 'The S locus controls white spotting patterns. Two copies of the s allele (s/s) typically produce the pied pattern.', NULL, 0, 1),

('genetics_colours', 'hard', 'What gene and locus is responsible for the merle pattern in dogs?', 'PMEL17 gene at the M locus', 'TYRP1 gene at the B locus', 'MLPH gene at the D locus', 'MC1R gene at the E locus', 'The merle pattern is caused by a mutation in the PMEL17 (SILV) gene at the M locus, creating patches of diluted colour.', NULL, 0, 1),
('genetics_colours', 'hard', 'What is an "Isabella" French Bulldog?', 'A double dilute carrying both blue (d/d) and testable chocolate (b/b)', 'A very light cream Frenchie', 'A red fawn with no mask', 'A brindle with unusual striping', 'Isabella, also known as "true lilac" or double dilute, requires two copies each of both the blue and testable chocolate genes.', 'Isabella Frenchies typically have milky brown coats and green or amber eyes.', 0, 1),
('genetics_colours', 'hard', 'What does "New Shade Isabella" mean in French Bulldog genetics?', 'A dog carrying d/d, b/b, and co/co (triple dilute)', 'A lighter version of standard Isabella', 'An Isabella with a black mask', 'An Isabella born from two standard parents', 'New Shade Isabella carries two copies each of blue (d/d), testable chocolate (b/b), and cocoa (co/co), creating a distinctive goldish-brown coat.', NULL, 0, 1),
('genetics_colours', 'hard', 'What A locus genotype produces tan points (tricolour) in French Bulldogs?', 'At/At or At/a', 'Ay/Ay', 'a/a', 'Aw/Aw', 'The At allele at the A locus produces the tan point pattern. Dogs that are At/At or At/a express tan points on legs, chest, cheeks, and eyebrows.', NULL, 0, 1),
('genetics_colours', 'hard', 'What is the "L gene" responsible for in French Bulldogs?', 'Long hair (fluffy coat)', 'Liver colouring', 'Large size', 'Light eyes', 'The L gene controls coat length. Two copies of the recessive l allele produce long-haired "fluffy" French Bulldogs.', NULL, 0, 1),
('genetics_colours', 'hard', 'What A locus genotype produces a solid non-brindle black French Bulldog?', 'a/a (recessive black)', 'At/At', 'Ay/Ay', 'Aw/Aw', 'Solid black (without brindle) is produced by the homozygous recessive a/a genotype at the A locus, combined with no brindle at the K locus.', NULL, 0, 1),
('genetics_colours', 'hard', 'Why can the merle pattern sometimes be "hidden" or invisible on a French Bulldog?', 'Other coat colours and patterns can mask the merle dilution effect', 'Merle fades as the dog ages', 'Merle only appears in sunlight', 'Merle is always visible', 'The merle coat pattern can hide under other colours, which is why genetic testing is critical before breeding to avoid accidental double merle matings.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 4: ANATOMY & APPEARANCE (35 questions)
-- ============================================================

('anatomy', 'easy', 'What is the signature ear shape that distinguishes French Bulldogs?', 'Bat ears (upright and rounded)', 'Rose ears (folded back)', 'Button ears (folded forward)', 'Drop ears (hanging down)', 'French Bulldogs are famous for their large, upright "bat ears," which American breeders fought to make the breed standard.', NULL, 0, 1),
('anatomy', 'easy', 'What is the maximum weight for a French Bulldog according to the AKC standard?', '28 pounds (13 kg)', '35 pounds (16 kg)', '20 pounds (9 kg)', '40 pounds (18 kg)', 'The AKC breed standard specifies a weight not to exceed 28 pounds.', NULL, 0, 1),
('anatomy', 'easy', 'What skull shape do French Bulldogs have?', 'Brachycephalic (flat-faced)', 'Dolichocephalic (long-snouted)', 'Mesocephalic (medium-length)', 'Pointed and narrow', 'Brachycephalic means "short-headed" — Frenchies have a flattened skull shape that creates their distinctive flat face.', NULL, 0, 1),
('anatomy', 'easy', 'What type of coat do French Bulldogs have?', 'Short, smooth, and fine', 'Long and fluffy', 'Wiry and rough', 'Double-coated and thick', 'The AKC standard describes the Frenchie coat as short-haired, fine, and silky.', NULL, 0, 1),
('anatomy', 'easy', 'What type of bite do French Bulldogs naturally have?', 'Undershot (underbite)', 'Overshot (overbite)', 'Scissor bite', 'Level bite', 'French Bulldogs naturally have an undershot jaw where the lower jaw protrudes beyond the upper jaw.', NULL, 0, 1),

('anatomy', 'medium', 'How tall is the average adult French Bulldog at the shoulder?', '11 to 13 inches (28-33 cm)', '15 to 18 inches (38-46 cm)', '8 to 10 inches (20-25 cm)', '20 to 24 inches (51-61 cm)', 'French Bulldogs are a compact, muscular breed standing 11-13 inches at the withers.', NULL, 0, 1),
('anatomy', 'medium', 'What type of tail do French Bulldogs naturally have?', 'Short, stumpy screw tail or straight tail', 'Long, curly tail', 'Docked (surgically shortened) tail', 'Pom-pom shaped tail', 'Frenchies are born with naturally short, stumpy tails that can be straight, screwed, or kinked. They are never docked.', NULL, 0, 1),
('anatomy', 'medium', 'How does the AKC standard describe the French Bulldog''s build?', 'Active, intelligent, muscular with heavy bone and compact structure', 'Lean, agile, and tall', 'Slender with long legs', 'Stocky with a long body', 'The standard calls for "an active, intelligent, muscular dog of heavy bone, smooth coat, compactly built."', NULL, 0, 1),
('anatomy', 'medium', 'What physical feature do French Bulldogs have around their neck and shoulders?', 'Soft, loose skin forming wrinkles', 'A thick mane of fur', 'A rigid, muscular ridge', 'A dewlap like a hound', 'Frenchies have characteristic loose, wrinkled skin around the neck and shoulders, as well as wrinkles on the face.', NULL, 0, 1),
('anatomy', 'medium', 'What eye colour does the AKC standard require for French Bulldogs?', 'Dark, almost black', 'Any colour including blue', 'Brown or hazel only', 'Amber or gold', 'The AKC standard specifies dark eyes, almost to the point of being black. Blue eyes are not AKC approved.', NULL, 0, 1),
('anatomy', 'medium', 'What is the distinctive expression that French Bulldogs show when panting?', 'A clownish, broad grin with visible flews', 'A serious, intense stare', 'A sleepy, droopy look', 'A wrinkled nose snarl', 'Frenchies are known for their comical expression when panting, created by their black flews (lips) and broad muzzle.', NULL, 0, 1),
('anatomy', 'medium', 'How is a French Bulldog''s head shape described in the breed standard?', 'Large and square', 'Small and round', 'Long and narrow', 'Flat and wide without structure', 'The AKC standard requires a large, square head with the characteristic bat ears.', NULL, 0, 1),

('anatomy', 'hard', 'What is the main physical difference between a French Bulldog and a Boston Terrier?', 'Frenchies are heavier-boned and more muscular with rounder bat ears', 'There is no significant difference', 'Boston Terriers are smaller', 'French Bulldogs have longer snouts', 'French Bulldogs are stockier, heavier-boned and more muscular than Boston Terriers. Frenchies have rounder bat ears while Bostons have more pointed ears.', NULL, 0, 1),
('anatomy', 'hard', 'At what angle should a French Bulldog''s bat ears be positioned according to the standard?', 'Broad at base, elongated, rounded at top, set high and carried erect', 'Pointed and close together on top of the head', 'Small, folded, and low-set', 'Large, floppy, and hanging to the side', 'The standard specifies ears that are broad at the base, elongated, with rounded tops, set high on the head and carried erect and parallel.', NULL, 0, 1),
('anatomy', 'hard', 'What term describes the roll of skin above a French Bulldog''s nose?', 'Nose rope or nasal fold', 'Muzzle wrap', 'Snout cap', 'Face pad', 'The roll of skin over the top of the muzzle is called the nose rope or nasal fold. It needs regular cleaning to prevent infections.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 5: PERSONALITY & BEHAVIOUR (36 questions)
-- ============================================================

('personality', 'easy', 'What is the most commonly used word to describe the French Bulldog''s personality?', 'Clownish', 'Aggressive', 'Shy', 'Hyperactive', 'Frenchies are universally described as clownish, playful, and entertaining. They love to make their owners laugh.', NULL, 0, 1),
('personality', 'easy', 'How many hours per day does an average adult French Bulldog sleep?', '12 to 14 hours', '6 to 8 hours', '18 to 20 hours', '4 to 6 hours', 'Frenchies are champion sleepers, typically sleeping 12-14 hours per day. Puppies sleep even more.', NULL, 0, 1),
('personality', 'easy', 'Are French Bulldogs known for excessive barking?', 'No, they are not frequent barkers', 'Yes, they bark constantly', 'They bark more than any other breed', 'They never make any sounds at all', 'Frenchies are not typically excessive barkers. However, they do "talk" with a variety of unique grumbles, groans, and other sounds.', NULL, 0, 1),
('personality', 'easy', 'How are French Bulldogs with children?', 'They are generally great with children', 'They should never be around children', 'They are aggressive toward children', 'They ignore children completely', 'French Bulldogs are known to be wonderful with children and are generally patient and playful family dogs.', NULL, 0, 1),
('personality', 'easy', 'What body sound are French Bulldogs famously known for producing besides snoring?', 'Farting (flatulence)', 'Howling', 'Whistling', 'Hiccupping', 'Frenchies are notoriously gassy due to their flat faces causing them to swallow air while eating, which has to find its way out.', NULL, 0, 1),

('personality', 'medium', 'What position do French Bulldogs often lie in, resembling an amphibian?', 'Frog legs (splooting)', 'Curled in a tight ball', 'Flat on their back', 'Standing on all fours', 'Many Frenchies lie flat with their back legs splayed out behind them, resembling a frog. This is called "splooting."', NULL, 0, 1),
('personality', 'medium', 'Why are French Bulldogs called "velcro dogs"?', 'They follow their owners everywhere and want constant closeness', 'Their fur sticks to furniture', 'They attach to other dogs quickly', 'Their paws grip surfaces well', 'Frenchies are known for extreme attachment to their owners, following them from room to room and wanting constant proximity.', NULL, 0, 1),
('personality', 'medium', 'What is a common behavioural issue in French Bulldogs when left alone too long?', 'Separation anxiety', 'Aggression toward objects', 'Excessive digging', 'Running away', 'As "velcro dogs" that crave human companionship, Frenchies are particularly prone to separation anxiety when left alone.', NULL, 0, 1),
('personality', 'medium', 'How do French Bulldogs typically communicate with their owners?', 'Through a variety of grumbles, groans, yips, and other unique vocalisations', 'Through loud, persistent barking', 'Through howling like wolves', 'They are completely silent', 'Frenchies are famous for their unique range of communicative sounds — grumbles, yawns, yaps, and what owners call "talking."', NULL, 0, 1),
('personality', 'medium', 'How much exercise does an adult French Bulldog need daily?', 'Moderate — short walks and play sessions', 'Intense — at least 2 hours of running', 'None — they are completely sedentary', 'Very high — they need hours of activity', 'Frenchies need moderate exercise with daily walks and play, but should avoid strenuous activity especially in heat.', NULL, 0, 1),
('personality', 'medium', 'Are French Bulldogs good for apartment living?', 'Yes, they are considered ideal apartment dogs', 'No, they need a large yard', 'Only if the apartment is on the ground floor', 'Only in quiet buildings', 'Their small size, low exercise needs, moderate noise level, and adaptable nature make Frenchies excellent apartment dogs.', 'Their suitability for urban living is one factor behind their modern popularity surge.', 0, 1),
('personality', 'medium', 'What makes French Bulldogs sometimes challenging to train?', 'Their stubborn and independent streak', 'They are not intelligent enough', 'They are too energetic to focus', 'They cannot hear commands well', 'Frenchies are intelligent but can be stubborn. They respond best to positive reinforcement with treats and patience rather than harsh methods.', NULL, 0, 1),
('personality', 'medium', 'What is the French Bulldog''s temperament officially described as?', 'Adaptable, playful, and alert', 'Guard-like and territorial', 'Timid and nervous', 'Aloof and independent', 'The breed is officially described as adaptable, playful, alert, and affectionate — true companion dogs.', NULL, 0, 1),

('personality', 'hard', 'Where do French Bulldogs approximately rank on Stanley Coren''s dog intelligence list?', 'Around 58th out of 138 breeds (average working intelligence)', 'Top 10 (extremely intelligent)', 'Last place (lowest intelligence)', 'Around 109th (below average)', 'French Bulldogs rank around 58th in obedience/working intelligence — average, but their stubbornness can make them appear less trainable.', 'Intelligence ranking only measures obedience; Frenchies show high adaptive and instinctive intelligence.', 0, 1),
('personality', 'hard', 'Why do French Bulldogs eat their food so quickly?', 'Their flat faces and excitement cause them to gulp food and air', 'They have faster metabolisms', 'They are always hungry due to a medical condition', 'Competition instinct from pack behaviour', 'The brachycephalic face shape makes it harder to pick up food efficiently, and their enthusiastic nature causes gulping, which also leads to flatulence.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 6: FAMOUS FRENCHIES (35 questions)
-- ============================================================

('famous_frenchies', 'easy', 'Which pop star had their French Bulldogs stolen in a 2021 dognapping incident?', 'Lady Gaga', 'Ariana Grande', 'Taylor Swift', 'Beyoncé', 'Lady Gaga''s dog walker was shot and two of her three French Bulldogs, Koji and Gustav, were stolen in February 2021. They were later recovered.', 'A reward of $500,000 was offered for their safe return.', 0, 1),
('famous_frenchies', 'easy', 'What AKC popularity ranking did French Bulldogs achieve in 2022?', 'Number 1 most popular breed in America', 'Number 5', 'Number 10', 'Number 3', 'In 2022, French Bulldogs overtook the Labrador Retriever to become the most popular breed in America, ending the Lab''s 31-year reign.', NULL, 0, 1),
('famous_frenchies', 'easy', 'Which famous actor known for action movies is a well-known French Bulldog owner?', 'Dwayne "The Rock" Johnson', 'Jason Statham', 'Arnold Schwarzenegger', 'Sylvester Stallone', 'The Rock is a well-known Frenchie lover who has shared many photos and stories about his French Bulldogs on social media.', NULL, 0, 1),
('famous_frenchies', 'easy', 'What was the name of the famous Instagram French Bulldog with over a million followers?', 'Manny the Frenchie', 'Doug the Pug', 'Boo the Pomeranian', 'Tuna the Chiweenie', 'Manny the Frenchie became one of the most famous dogs on social media, amassing millions of followers.', NULL, 0, 1),
('famous_frenchies', 'easy', 'Which breed did the French Bulldog overtake to become America''s #1 breed?', 'Labrador Retriever', 'German Shepherd', 'Golden Retriever', 'Poodle', 'The Labrador Retriever had been #1 for 31 consecutive years before the French Bulldog took the top spot.', NULL, 0, 1),

('famous_frenchies', 'medium', 'Which famous fashion designer was devoted to his French Bulldog named Moujik?', 'Yves Saint Laurent', 'Karl Lagerfeld', 'Ralph Lauren', 'Tom Ford', 'Yves Saint Laurent was famously devoted to his French Bulldog Moujik, who accompanied him nearly everywhere.', 'Karl Lagerfeld was actually famous for his Birman cat, Choupette.', 0, 1),
('famous_frenchies', 'medium', 'Which Australian actor and Wolverine star is a French Bulldog owner?', 'Hugh Jackman', 'Chris Hemsworth', 'Russell Crowe', 'Liam Hemsworth', 'Hugh Jackman has been spotted with French Bulldogs and is a known fan of the breed.', NULL, 0, 1),
('famous_frenchies', 'medium', 'For how many consecutive years did the Labrador Retriever hold the #1 spot before the Frenchie took over?', '31 years', '10 years', '20 years', '50 years', 'Labrador Retrievers held the top spot from 1991 to 2022, a 31-year reign ended by the French Bulldog.', NULL, 0, 1),
('famous_frenchies', 'medium', 'What is the French Bulldog''s popularity ranking in the United Kingdom?', 'One of the top 3 most popular breeds', 'Around 20th', 'The most popular breed', 'Not in the top 50', 'French Bulldogs are consistently one of the top 2-3 most popular breeds in the UK by KC registrations.', NULL, 0, 1),
('famous_frenchies', 'medium', 'What major event in 2021 brought French Bulldog theft into the national spotlight?', 'Lady Gaga''s dog walker was shot during a dognapping', 'A French Bulldog was stolen from the White House', 'A celebrity''s Frenchie was taken at an airport', 'A famous breeder''s entire litter was stolen', 'The violent theft of Lady Gaga''s dogs in February 2021, where her dog walker Ryan Fischer was shot, drew massive attention to the problem of Frenchie theft.', NULL, 0, 1),
('famous_frenchies', 'medium', 'Which former British footballer''s family is known for owning French Bulldogs?', 'David Beckham', 'Wayne Rooney', 'Frank Lampard', 'Steven Gerrard', 'The Beckham family are well-known French Bulldog owners.', NULL, 0, 1),
('famous_frenchies', 'medium', 'In what year did the AKC confirm the French Bulldog was still #1 most popular?', '2024', '2020', '2021', '2019', 'The AKC confirmed the French Bulldog remained the most popular dog breed in both 2023 and 2024.', NULL, 0, 1),

('famous_frenchies', 'hard', 'How much could French Bulldogs sell for during the Gilded Age in the early 1900s?', 'Up to $3,000 (enormous sum at the time)', 'About $50', 'Around $500', 'Up to $10,000', 'In the early 20th century, French Bulldogs were status symbols that could change hands for up to $3,000, equivalent to tens of thousands today.', NULL, 0, 1),
('famous_frenchies', 'hard', 'In what year was the French Bulldog ranked as the 4th most popular AKC breed?', '2018', '2015', '2020', '2010', 'The French Bulldog reached 4th place in AKC registrations in 2018, continuing its rapid climb that started in the 2000s.', NULL, 0, 1),
('famous_frenchies', 'hard', 'What was the French Bulldog''s AKC ranking in the year 1906?', '5th most popular', '1st most popular', '20th most popular', '50th most popular', 'By 1906, the French Bulldog was already the fifth most popular dog breed in America during its first wave of popularity.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 7: PUPPY CARE (30 questions)
-- ============================================================

('puppy_care', 'easy', 'At what age do French Bulldog puppies'' ears typically stand up permanently?', '8 to 15 weeks', '2 to 4 weeks', '6 to 12 months', 'They are born with upright ears', 'Frenchie puppies are born with floppy ears that gradually stand up as the ear cartilage strengthens, usually between 8-15 weeks.', NULL, 0, 1),
('puppy_care', 'easy', 'How many puppies are typically in a French Bulldog litter?', '2 to 4 puppies', '6 to 8 puppies', '8 to 12 puppies', '1 puppy only', 'French Bulldogs typically have small litters of 2-4 puppies, with 3 being the most common.', NULL, 0, 1),
('puppy_care', 'easy', 'Why should Frenchie puppies avoid strenuous exercise on hot days?', 'Their flat faces make breathing difficult and they overheat easily', 'Their bones are too fragile until age 2', 'Exercise causes their ears to droop', 'They are naturally lazy and will refuse', 'Brachycephalic breeds cannot pant as efficiently, making them highly susceptible to heatstroke during exercise.', NULL, 0, 1),
('puppy_care', 'easy', 'What is the best time to begin socialising a French Bulldog puppy?', 'Between 3 and 14 weeks of age', 'After 6 months old', 'Only after all vaccinations at 16 weeks', 'At 1 year old', 'The critical socialisation window is 3-14 weeks. Exposing puppies to various people, sounds, and experiences during this time is crucial.', NULL, 0, 1),
('puppy_care', 'easy', 'How often should a French Bulldog puppy be fed?', '3 to 4 times per day', 'Once per day', 'Twice per day', 'Free feeding all day', 'Young Frenchie puppies need 3-4 small meals per day. This can be reduced to 2 meals per day as adults.', NULL, 0, 1),

('puppy_care', 'medium', 'Why do most French Bulldog puppies need to be born via C-section?', 'Their large heads are too big for the mother''s narrow pelvis', 'Frenchie mothers refuse to give birth naturally', 'The puppies are too long', 'Veterinarians prefer it for convenience', 'The broad head and shoulders of the puppies relative to the mother''s narrow hips make natural birth extremely difficult and dangerous.', NULL, 0, 1),
('puppy_care', 'medium', 'At what age should a French Bulldog puppy receive its first vaccination?', '6 to 8 weeks', '2 weeks', '12 weeks', '6 months', 'Core vaccinations typically begin at 6-8 weeks of age with boosters given at regular intervals.', NULL, 0, 1),
('puppy_care', 'medium', 'What is the typical weight of a newborn French Bulldog puppy?', '8 to 14 ounces (225-400g)', '2 to 3 pounds (1-1.5 kg)', '4 to 6 ounces (110-170g)', '1 to 2 pounds (450-900g)', 'Frenchie puppies are born very small, typically weighing between 8-14 ounces.', NULL, 0, 1),
('puppy_care', 'medium', 'Why is crate training particularly beneficial for French Bulldog puppies?', 'It helps with house training and provides a safe den space', 'Frenchies are too dangerous to be loose', 'It makes them more aggressive', 'It stunts their growth', 'Crate training gives Frenchie puppies a safe space and helps with house training, which can be challenging with this stubborn breed.', NULL, 0, 1),
('puppy_care', 'medium', 'When do French Bulldog puppies start teething?', 'Around 3 to 4 months old', 'At birth', 'At 6 months old', 'At 1 year old', 'Frenchie puppies begin losing baby teeth and getting adult teeth around 3-4 months. Provide appropriate chew toys during this stage.', NULL, 0, 1),
('puppy_care', 'medium', 'How much should a French Bulldog puppy weigh at 3 months old?', 'About 8 to 12 pounds (3.5-5.5 kg)', '2 to 4 pounds (1-2 kg)', '15 to 20 pounds (7-9 kg)', '20 to 25 pounds (9-11 kg)', 'A healthy 3-month-old Frenchie puppy typically weighs around 8-12 pounds, about one-third to half of their adult weight.', NULL, 0, 1),
('puppy_care', 'medium', 'At what age is a French Bulldog considered fully grown?', 'Around 12 to 14 months', '6 months', '3 years', '2 years', 'Most French Bulldogs reach their adult height by 9-12 months and fill out to adult weight by 12-14 months.', NULL, 0, 1),

('puppy_care', 'hard', 'What is the "neonatal period" in French Bulldog puppy development?', 'Birth to 2 weeks — puppies are blind, deaf, and fully dependent', '2 to 4 weeks — puppies begin walking', '4 to 8 weeks — puppies start eating solid food', '8 to 12 weeks — puppies are weaned', 'During the neonatal period (0-2 weeks), puppies cannot see or hear and are completely dependent on their mother for warmth and nutrition.', NULL, 0, 1),
('puppy_care', 'hard', 'What percentage of French Bulldog puppies are conceived through artificial insemination?', 'A large majority, as natural mating is difficult', 'Less than 10%', 'About 50%', 'Almost none — natural mating is preferred', 'Due to the Frenchie''s compact body structure, many breeders use artificial insemination as natural mating can be difficult.', NULL, 0, 1),
('puppy_care', 'hard', 'Why might one ear stand up before the other in a Frenchie puppy?', 'Each ear develops cartilage strength at its own pace; this is normal', 'The puppy has a birth defect', 'The puppy slept on one side too much', 'One ear will never stand up', 'It is perfectly normal for one ear to stand up before the other. Both ears typically stand erect by 15 weeks.', NULL, 0, 1);

-- ============================================================
-- CATEGORY 8: NUTRITION & DIET (32 questions)
-- ============================================================

INSERT INTO questions (category, difficulty, question, correct_answer, incorrect_answer_1, incorrect_answer_2, incorrect_answer_3, explanation, fun_fact, is_premium, is_active) VALUES

('nutrition', 'easy', 'Which common human food is toxic to French Bulldogs and all dogs?', 'Chocolate', 'Chicken', 'Rice', 'Carrots', 'Chocolate contains theobromine, which dogs cannot metabolise effectively. Dark chocolate is the most dangerous type.', NULL, 0, 1),
('nutrition', 'easy', 'Which fruit is toxic to dogs and should never be fed to a Frenchie?', 'Grapes and raisins', 'Apples', 'Bananas', 'Watermelon', 'Grapes and raisins can cause kidney failure in dogs, even in small amounts.', NULL, 0, 1),
('nutrition', 'easy', 'How many meals per day should an adult French Bulldog eat?', '2 meals per day', '1 large meal', '4 small meals', 'Free feeding all day', 'Most veterinarians recommend feeding adult Frenchies twice daily with measured portions.', NULL, 0, 1),
('nutrition', 'easy', 'Are French Bulldogs prone to obesity?', 'Yes, they gain weight easily and need portion control', 'No, they never gain excess weight', 'Only if they eat human food', 'Only senior Frenchies are at risk', 'Frenchies love food and have lower exercise needs, making them prone to weight gain without careful portion control.', NULL, 0, 1),
('nutrition', 'easy', 'What vegetable-family food is toxic to all dogs including Frenchies?', 'Onions and garlic', 'Carrots', 'Green beans', 'Pumpkin', 'Onions, garlic, leeks, and chives can damage red blood cells in dogs, causing anaemia.', NULL, 0, 1),

('nutrition', 'medium', 'What is the most common food allergen for French Bulldogs?', 'Beef protein', 'Rice', 'Sweet potato', 'Fish', 'Beef is the most common food allergen in dogs, followed by dairy and chicken. Frenchies are particularly prone to food sensitivities.', NULL, 0, 1),
('nutrition', 'medium', 'What is the recommended daily calorie intake for a 25-pound adult French Bulldog?', '500 to 600 calories', '200 to 300 calories', '800 to 1000 calories', '1200 to 1500 calories', 'A 25-pound moderately active Frenchie needs about 500-600 calories per day. Overfeeding is very common.', NULL, 0, 1),
('nutrition', 'medium', 'What sugar substitute is extremely toxic to dogs?', 'Xylitol', 'Stevia', 'Sucralose', 'Honey', 'Xylitol, found in sugar-free gum, candy, and some peanut butters, causes a rapid release of insulin in dogs, leading to liver failure.', NULL, 0, 1),
('nutrition', 'medium', 'Why do French Bulldogs produce so much flatulence?', 'Their flat faces cause them to swallow excess air while eating', 'They have a unique digestive enzyme', 'All small dogs are equally gassy', 'They eat too fast by choice', 'The brachycephalic face shape makes Frenchies gulp air while eating, which leads to their notorious flatulence.', 'Using a slow-feeder bowl can help reduce air intake and gas.', 0, 1),
('nutrition', 'medium', 'What type of nut is toxic to dogs?', 'Macadamia nuts', 'Peanuts', 'Cashews', 'Almonds', 'Macadamia nuts are uniquely toxic to dogs and can cause vomiting, tremors, hyperthermia, and weakness.', NULL, 0, 1),
('nutrition', 'medium', 'What omega fatty acid is particularly beneficial for French Bulldog skin health?', 'Omega-3 fatty acids (from fish oil)', 'Omega-9 fatty acids', 'Omega-7 fatty acids', 'Omega-12 fatty acids', 'Omega-3 fatty acids from fish oil help reduce inflammation and support healthy skin and coat, which is especially beneficial for allergy-prone Frenchies.', NULL, 0, 1),
('nutrition', 'medium', 'Why might a limited-ingredient diet be recommended for a French Bulldog?', 'To identify and eliminate food allergens', 'Because Frenchies need fewer nutrients', 'To save money on food', 'Because their stomachs are too small for variety', 'Limited-ingredient diets help identify which specific proteins or ingredients are causing allergic reactions by eliminating variables.', NULL, 0, 1),
('nutrition', 'medium', 'What tool can help reduce a French Bulldog''s gas and bloating from eating too fast?', 'A slow-feeder bowl', 'A heated food bowl', 'An elevated feeder', 'A timed automatic feeder', 'Slow-feeder bowls have ridges or puzzles that force dogs to eat more slowly, reducing the amount of air swallowed.', NULL, 0, 1),

('nutrition', 'hard', 'What percentage of a French Bulldog''s daily calories should come from protein?', 'At least 25-30%', 'Less than 10%', '50-60%', '5-15%', 'Dogs need a protein-rich diet with at least 25-30% of calories from high-quality protein sources for muscle maintenance and overall health.', NULL, 0, 1),
('nutrition', 'hard', 'What artificial sweetener-free fruit is safe and beneficial for Frenchies as a treat?', 'Blueberries', 'Grapes', 'Cherries with pits', 'Avocado', 'Blueberries are safe, low-calorie, antioxidant-rich treats for dogs. They also provide fibre and vitamins C and K.', NULL, 0, 1),
('nutrition', 'hard', 'Why is avocado potentially harmful to dogs?', 'It contains persin, which can cause vomiting and diarrhoea', 'It is too high in sugar', 'It causes immediate allergic reactions in all dogs', 'It has no nutritional value for dogs', 'Avocado contains persin, a fungicidal toxin that can cause gastrointestinal distress in dogs. The pit also poses a choking hazard.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 9: TRAINING TIPS (28 questions)
-- ============================================================

('training', 'easy', 'What training method works best for French Bulldogs?', 'Positive reinforcement with treats and praise', 'Strict discipline and punishment', 'Ignoring bad behaviour completely', 'Physical corrections', 'Frenchies respond best to positive reinforcement. Their stubborn nature makes punishment-based methods counterproductive.', NULL, 0, 1),
('training', 'easy', 'What is the ideal length for a French Bulldog training session?', '5 to 10 minutes', '30 to 60 minutes', '2 to 3 hours', '1 to 2 minutes', 'Short, frequent sessions work best for Frenchies as they can lose interest quickly. Multiple 5-10 minute sessions are ideal.', NULL, 0, 1),
('training', 'easy', 'What motivates French Bulldogs most during training?', 'High-value food treats', 'Verbal praise only', 'Toy rewards', 'Fear of punishment', 'Frenchies are highly food-motivated, making treats the most effective training reward. Use small, soft treats for quick consumption.', NULL, 0, 1),

('training', 'medium', 'Why can French Bulldogs be more challenging to house-train than many other breeds?', 'Their natural stubbornness and independent thinking', 'They have very small bladders', 'They cannot go outside in cold weather', 'They prefer indoor elimination', 'Frenchies are known for their stubborn streak, which can make house training take longer. Consistency, patience, and positive reinforcement are essential.', NULL, 0, 1),
('training', 'medium', 'What is clicker training and why is it effective for Frenchies?', 'Using a clicking device to mark correct behaviour instantly, paired with treats', 'Clicking your fingers to get their attention', 'A type of punishment-based training', 'Training with music in the background', 'Clicker training provides precise timing for marking desired behaviours, making it easier for stubborn Frenchies to understand what earns rewards.', NULL, 0, 1),
('training', 'medium', 'What common behavioural issue should French Bulldog owners address early?', 'Jumping up on people', 'Excessive running', 'Climbing trees', 'Digging deep holes', 'Frenchies love attention and often jump on people to greet them. Teaching "four on the floor" or a sit-to-greet early prevents this habit.', NULL, 0, 1),
('training', 'medium', 'Why is early socialisation especially important for French Bulldogs?', 'It prevents fearfulness and aggression toward unfamiliar situations', 'It makes them run faster', 'It helps their ears stand up', 'It improves their coat colour', 'Without proper socialisation, Frenchies can become fearful or reactive. Early exposure to varied people, animals, and environments builds confidence.', NULL, 0, 1),
('training', 'medium', 'What approach works best for teaching a French Bulldog to walk on a leash?', 'Short, positive sessions with treats for walking beside you', 'Pulling them along until they learn', 'Using a retractable leash with no structure', 'Waiting until they are fully grown', 'Patient, reward-based leash training works best. Frenchies can pull, so teaching loose-leash walking early is important.', NULL, 0, 1),
('training', 'medium', 'What is "resource guarding" and why should Frenchie owners watch for it?', 'Protective behaviour over food, toys, or space that can escalate to aggression', 'Guarding the house from intruders', 'Protecting other pets in the household', 'Hiding toys in their crate', 'Some Frenchies develop resource guarding where they growl or snap when someone approaches their food or favourite items. Early intervention is key.', NULL, 0, 1),

('training', 'hard', 'What is "shaping" in dog training and how does it apply to French Bulldogs?', 'Rewarding successive approximations of a desired behaviour in small steps', 'Physically positioning the dog into the correct posture', 'Using a mould to shape their body position', 'Training them to recognise shapes and patterns', 'Shaping works well for stubborn Frenchies as it breaks complex behaviours into tiny, achievable steps that are individually rewarded.', NULL, 0, 1),
('training', 'hard', 'Why is it important to avoid using choke chains or prong collars on French Bulldogs?', 'Their compromised airways make neck pressure dangerous', 'They are too small for these collars', 'It ruins their coat', 'It is illegal everywhere', 'Brachycephalic breeds already have breathing difficulties. Pressure on the neck from aversive collars can further restrict their airway and cause injury.', 'A well-fitted harness is recommended instead.', 0, 1),

-- ============================================================
-- CATEGORY 10: FRENCHIE VS THE WORLD (30 questions)
-- ============================================================

('frenchie_vs_world', 'easy', 'Which breed did the French Bulldog overtake as America''s most popular in 2022?', 'Labrador Retriever', 'German Shepherd', 'Golden Retriever', 'Beagle', 'The Labrador Retriever had been #1 for 31 years before the French Bulldog took the top spot.', NULL, 0, 1),
('frenchie_vs_world', 'easy', 'Which breed is the French Bulldog most closely related to?', 'English Bulldog', 'Boston Terrier', 'Pug', 'Boxer', 'French Bulldogs descended directly from English Bulldogs, specifically the miniature/toy bulldog variety.', NULL, 0, 1),
('frenchie_vs_world', 'easy', 'How does a French Bulldog''s size compare to an English Bulldog?', 'French Bulldogs are significantly smaller and lighter', 'They are the same size', 'French Bulldogs are larger', 'French Bulldogs are taller but lighter', 'French Bulldogs weigh up to 28 lbs while English Bulldogs weigh 40-50+ lbs. Frenchies are also shorter.', NULL, 0, 1),

('frenchie_vs_world', 'medium', 'How does the French Bulldog''s lifespan compare to the English Bulldog?', 'Frenchies typically live 2-3 years longer (10-12 vs 8-10)', 'They have about the same lifespan', 'English Bulldogs live significantly longer', 'Frenchies live about 5 years longer', 'French Bulldogs average 10-12 years while English Bulldogs average 8-10 years.', NULL, 0, 1),
('frenchie_vs_world', 'medium', 'What is the key ear difference between a French Bulldog and a Boston Terrier?', 'Frenchies have rounded bat ears; Bostons have more pointed, erect ears', 'They have the same ears', 'Bostons have floppy ears', 'Frenchies have smaller ears', 'French Bulldogs have wider, more rounded "bat ears" while Boston Terriers have more pointed, triangular erect ears.', NULL, 0, 1),
('frenchie_vs_world', 'medium', 'How does the French Bulldog''s exercise needs compare to a Labrador Retriever?', 'Frenchies need much less exercise than Labs', 'They need the same amount', 'Frenchies need more exercise', 'Labs need less exercise', 'Labradors are high-energy sporting dogs needing 1-2 hours of vigorous exercise daily, while Frenchies need only moderate walks and play.', NULL, 0, 1),
('frenchie_vs_world', 'medium', 'Which other brachycephalic breed is the French Bulldog most often confused with?', 'Boston Terrier', 'Pekingese', 'Shih Tzu', 'Cavalier King Charles Spaniel', 'French Bulldogs and Boston Terriers are frequently confused due to similar size, colouring, and flat faces. Key differences are body type and ear shape.', NULL, 0, 1),
('frenchie_vs_world', 'medium', 'How does the Pug compare to the French Bulldog in weight?', 'Pugs are lighter, typically 14-18 lbs vs Frenchies at 16-28 lbs', 'They weigh the same', 'Pugs are heavier', 'Pugs weigh about twice as much', 'Pugs are a lighter breed at 14-18 pounds, while French Bulldogs are heavier and more muscular at 16-28 pounds.', NULL, 0, 1),
('frenchie_vs_world', 'medium', 'What nickname distinguishes the French Bulldog from the English Bulldog?', 'Frenchie', 'Bully', 'Frenchy Bull', 'Little Bull', 'The French Bulldog is affectionately known as "Frenchie" while the English Bulldog is often just called "Bulldog."', NULL, 0, 1),

('frenchie_vs_world', 'hard', 'Approximately how many AKC registrations did French Bulldogs have in 2024?', 'Over 108,000', 'About 20,000', 'About 50,000', 'About 200,000', 'French Bulldog registrations have grown explosively, with over 108,000 AKC registrations recorded recently.', NULL, 0, 1),
('frenchie_vs_world', 'hard', 'What is the main body proportion difference between a French Bulldog and a Boston Terrier?', 'Frenchies are wider, heavier-boned and more muscular; Bostons are leaner and longer-legged', 'Bostons are stockier', 'They have identical proportions', 'Frenchies have longer legs', 'French Bulldogs have a wider, more muscular, heavy-boned build compared to the lighter, more elegant, longer-legged Boston Terrier.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 11: POP CULTURE (28 questions)
-- ============================================================

('pop_culture', 'easy', 'What type of social media content featuring Frenchies goes most viral?', 'Funny snoring and sleeping videos', 'Agility course competitions', 'Swimming videos', 'Long-distance running clips', 'Frenchie content is hugely popular on TikTok and Instagram, with snoring, splooting, and goofy behaviour videos regularly going viral.', NULL, 0, 1),
('pop_culture', 'easy', 'On which platform do French Bulldog videos get billions of views?', 'TikTok', 'LinkedIn', 'Twitter/X', 'Pinterest', 'The #frenchbulldog hashtag has accumulated billions of views on TikTok.', NULL, 0, 1),
('pop_culture', 'easy', 'What factor has most contributed to the French Bulldog''s modern popularity explosion?', 'Social media and celebrity ownership', 'New health breakthroughs', 'Government subsidies for the breed', 'They became cheaper to buy', 'The rise of social media platforms and high-profile celebrity ownership created a massive surge in demand for Frenchies.', NULL, 0, 1),

('pop_culture', 'medium', 'Approximately how many views does the #frenchbulldog hashtag have on TikTok?', 'Over 17 billion', 'About 1 billion', 'About 500 million', 'Over 50 billion', 'The #frenchbulldog hashtag has accumulated over 17 billion views on TikTok, making it one of the most popular dog breed hashtags.', NULL, 0, 1),
('pop_culture', 'medium', 'Why has the rise in French Bulldog popularity led to increased dog theft?', 'Their high price tag makes them targets for criminals', 'There is a Frenchie shortage', 'They are easy to train as guard dogs', 'They are rare and hard to breed', 'French Bulldogs can sell for thousands of dollars, making them a target for theft. The Lady Gaga incident highlighted this problem.', NULL, 0, 1),
('pop_culture', 'medium', 'What trait makes French Bulldogs particularly suited to social media stardom?', 'Their expressive faces and funny sounds create entertaining content', 'Their ability to perform tricks', 'Their speed and agility', 'Their large size', 'Frenchies have incredibly expressive faces, make unique sounds, and have naturally comical behaviours that translate well to short-form video content.', NULL, 0, 1),
('pop_culture', 'medium', 'Which famous French Impressionist-era artist painted French Bulldogs in his works?', 'Henri de Toulouse-Lautrec', 'Claude Monet', 'Paul Cézanne', 'Edgar Degas', 'Toulouse-Lautrec featured French Bulldogs in his famous paintings of Montmartre nightlife in the late 1800s.', 'Degas is also thought to have included Frenchies in some of his works.', 0, 1),
('pop_culture', 'medium', 'What risqué association did French Bulldogs have in early 20th century Paris?', 'They appeared on postcards with the ladies of Montmartre', 'They were used in circus performances', 'They were racing dogs', 'They were banned from polite society', 'French Bulldogs became associated with bohemian Parisian culture and appeared on risqué postcards alongside the women of Montmartre.', NULL, 0, 1),

('pop_culture', 'hard', 'What impact has French Bulldog popularity had on veterinary emergency rooms?', 'Significant increase in BOAS and heat-related emergencies', 'No measurable impact', 'Decrease in emergency visits', 'Increase in vaccination visits only', 'The explosion of Frenchie ownership has led to a notable increase in brachycephalic-related emergencies at veterinary hospitals.', NULL, 0, 1),
('pop_culture', 'hard', 'What ethical concern has the French Bulldog''s popularity raised among veterinary organisations?', 'Concerns about breeding for extreme features that cause health problems', 'Concerns about Frenchies being too smart', 'Concerns about them being too expensive', 'Concerns about noise pollution from barking', 'Multiple veterinary organisations have raised concerns about the health consequences of breeding for increasingly flat faces and compact bodies.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 12: TRUE OR FALSE (35 questions)
-- ============================================================

('true_or_false', 'easy', 'True or False: French Bulldogs were originally bred in France.', 'False — they originated in England', 'True', NULL, NULL, 'Despite their name, French Bulldogs descended from English Bulldogs. Lace workers brought them to France during the Industrial Revolution.', NULL, 0, 1),
('true_or_false', 'easy', 'True or False: French Bulldogs are excellent swimmers.', 'False — they are poor swimmers due to their body shape', 'True', NULL, NULL, 'Frenchies are top-heavy with a large head and chest, short legs, and flat faces, making swimming very dangerous without a life vest.', NULL, 0, 1),
('true_or_false', 'easy', 'True or False: French Bulldogs are hypoallergenic.', 'False — no dog breed is truly hypoallergenic, and Frenchies do shed', 'True', NULL, NULL, 'While Frenchies have short coats, they are not hypoallergenic. They shed regularly and produce dander like all dogs.', NULL, 0, 1),
('true_or_false', 'easy', 'True or False: All French Bulldogs snore.', 'True — virtually all Frenchies snore due to their flat faces', 'False', NULL, NULL, 'Due to their brachycephalic anatomy, snoring is extremely common and considered normal for the breed.', NULL, 0, 1),
('true_or_false', 'easy', 'True or False: French Bulldogs need a lot of exercise.', 'False — they need only moderate exercise', 'True', NULL, NULL, 'Frenchies are not high-energy dogs. Short daily walks and play sessions are sufficient, and they should avoid strenuous activity.', NULL, 0, 1),

('true_or_false', 'medium', 'True or False: Most French Bulldogs can give birth naturally.', 'False — over 80% require C-sections', 'True', NULL, NULL, 'Due to the puppies'' large heads relative to the mother''s narrow pelvis, the vast majority of Frenchie births require surgical delivery.', NULL, 0, 1),
('true_or_false', 'medium', 'True or False: Blue (grey) French Bulldogs are recognised by the AKC.', 'False — blue/mouse is a disqualifying colour', 'True', NULL, NULL, 'The AKC breed standard lists "mouse" (the blue-grey colour) as a disqualification for conformation shows.', NULL, 0, 1),
('true_or_false', 'medium', 'True or False: French Bulldogs have been banned from some airlines.', 'True — many airlines restrict brachycephalic breeds from cargo', 'False', NULL, NULL, 'Multiple airlines have restricted or banned brachycephalic breeds from cargo holds due to significantly higher respiratory risk during flights.', NULL, 0, 1),
('true_or_false', 'medium', 'True or False: A French Bulldog''s tail is naturally short and is never docked.', 'True — they are born with naturally short tails', 'False', NULL, NULL, 'Frenchies are born with naturally short, stumpy tails that can be straight, screwed, or kinked. Tail docking is never performed.', NULL, 0, 1),
('true_or_false', 'medium', 'True or False: French Bulldogs are good watchdogs.', 'True — they are alert and will bark to alert owners of strangers', 'False', NULL, NULL, 'While not aggressive guard dogs, Frenchies are alert and will bark to notify their owners of someone at the door or unusual activity.', NULL, 0, 1),
('true_or_false', 'medium', 'True or False: Merle is an AKC-approved colour for French Bulldogs.', 'False — merle is a disqualifying colour/pattern', 'True', NULL, NULL, 'Merle is not an accepted pattern in the AKC French Bulldog breed standard and results in disqualification from conformation shows.', NULL, 0, 1),
('true_or_false', 'medium', 'True or False: French Bulldogs can safely fly in airplane cargo holds.', 'False — cargo travel is extremely risky for brachycephalic breeds', 'True', NULL, NULL, 'The pressurised cargo hold poses significant respiratory risks for flat-faced breeds. Many airlines have banned them from cargo altogether.', NULL, 0, 1),
('true_or_false', 'medium', 'True or False: French Bulldogs were once the 5th most popular breed in America in the early 1900s.', 'True — they were 5th by 1906', 'False', NULL, NULL, 'By 1906, the French Bulldog had climbed to 5th place in AKC registrations during their first wave of American popularity.', NULL, 0, 1),
('true_or_false', 'medium', 'True or False: French Bulldogs are closely related to Pugs.', 'False — they descended from English Bulldogs, not Pugs', 'True', NULL, NULL, 'While pugs may have been cross-bred into early lines in France, the French Bulldog is a direct descendant of the English Bulldog family.', NULL, 0, 1),

('true_or_false', 'hard', 'True or False: The brindle French Bulldog colour was the only accepted colour in the original 1897 standard.', 'True — fawn, cream, and piebald were added in 1911', 'False', NULL, NULL, 'The initial 1897 breed standard only accepted brindle. The standard was amended in 1911 to include additional colours.', NULL, 0, 1),
('true_or_false', 'hard', 'True or False: White French Bulldogs have a higher risk of deafness.', 'True — extreme white piebald colouring is associated with congenital deafness', 'False', NULL, NULL, 'Dogs with predominantly white coats, especially extreme white piebald, have a higher incidence of congenital deafness linked to lack of pigment cells in the inner ear.', NULL, 0, 1),
('true_or_false', 'hard', 'True or False: The French Bull Dog Club of America was the first breed-specific club in the world to hold a specialty show.', 'True — at the Waldorf-Astoria in 1898', 'False', NULL, NULL, 'The FBDCA held the world''s first breed-specific specialty show at the Waldorf-Astoria hotel in New York in 1898.', NULL, 0, 1),
('true_or_false', 'hard', 'True or False: Breeding two merle French Bulldogs together is considered safe.', 'False — it can cause severe health defects in puppies', 'True', NULL, NULL, 'Double merle (homozygous merle) breeding significantly increases the risk of deafness, blindness, and other serious health problems.', NULL, 0, 1),
('true_or_false', 'hard', 'True or False: French Bulldogs have a third eyelid.', 'True — all dogs have a third eyelid (nictitating membrane)', 'False', NULL, NULL, 'Dogs have a third eyelid called the nictitating membrane. When its gland prolapses, it causes "cherry eye," which is common in Frenchies.', NULL, 0, 1),

-- ============================================================
-- CATEGORY 13: SPEED ROUND (30 questions)
-- ============================================================

('speed_round', 'easy', 'What shape are a French Bulldog''s ears?', 'Bat-shaped', 'Floppy', 'Pointed', 'Rose-shaped', NULL, NULL, 0, 1),
('speed_round', 'easy', 'Do French Bulldogs have long or short tails?', 'Short', 'Long', NULL, NULL, NULL, NULL, 0, 1),
('speed_round', 'easy', 'Are French Bulldogs a small, medium, or large breed?', 'Small', 'Medium', 'Large', 'Giant', NULL, NULL, 0, 1),
('speed_round', 'easy', 'What sound are Frenchies famous for making while sleeping?', 'Snoring', 'Howling', 'Barking', 'Whistling', NULL, NULL, 0, 1),
('speed_round', 'easy', 'What continent did French Bulldogs originate from?', 'Europe', 'Asia', 'North America', 'South America', NULL, NULL, 0, 1),
('speed_round', 'easy', 'Can French Bulldogs swim without a life vest?', 'No — they are very poor swimmers', 'Yes, they are excellent swimmers', NULL, NULL, NULL, NULL, 0, 1),
('speed_round', 'easy', 'What is the nickname for French Bulldogs?', 'Frenchie', 'Frenchy', 'FB', 'Bulldog Jr', NULL, NULL, 0, 1),
('speed_round', 'easy', 'Are Frenchies good with kids?', 'Yes', 'No', NULL, NULL, NULL, NULL, 0, 1),
('speed_round', 'easy', 'What colour is NOT accepted by the AKC: fawn, brindle, or blue?', 'Blue', 'Fawn', 'Brindle', NULL, NULL, NULL, 0, 1),
('speed_round', 'easy', 'Do Frenchies bark a lot?', 'No', 'Yes', NULL, NULL, NULL, NULL, 0, 1),
('speed_round', 'easy', 'What position is "splooting"?', 'Lying flat with back legs splayed out like a frog', 'Standing on hind legs', 'Sitting upright', 'Rolling on their back', NULL, NULL, 0, 1),
('speed_round', 'easy', 'Is the French Bulldog currently the #1 breed in America?', 'Yes', 'No', NULL, NULL, NULL, NULL, 0, 1),
('speed_round', 'easy', 'How many hours a day do Frenchies typically sleep?', '12 to 14', '5 to 6', '18 to 20', '8 to 9', NULL, NULL, 0, 1),
('speed_round', 'easy', 'What is a French Bulldog''s skull shape called?', 'Brachycephalic', 'Dolichocephalic', 'Mesocephalic', NULL, NULL, NULL, 0, 1),
('speed_round', 'easy', 'True or false: Frenchies were originally bred in France.', 'False — England', 'True', NULL, NULL, NULL, NULL, 0, 1),

('speed_round', 'medium', 'What is the AKC maximum weight for a French Bulldog?', '28 pounds', '35 pounds', '20 pounds', '40 pounds', NULL, NULL, 0, 1),
('speed_round', 'medium', 'What year did Frenchies become America''s #1 breed?', '2022', '2020', '2018', '2024', NULL, NULL, 0, 1),
('speed_round', 'medium', 'What breed was #1 before the Frenchie?', 'Labrador Retriever', 'German Shepherd', 'Golden Retriever', 'Poodle', NULL, NULL, 0, 1),
('speed_round', 'medium', 'How many puppies in a typical Frenchie litter?', '2 to 4', '6 to 8', '8 to 10', '1', NULL, NULL, 0, 1),
('speed_round', 'medium', 'What percentage of Frenchie births are by C-section?', 'Over 80%', '50%', '30%', '10%', NULL, NULL, 0, 1),

('speed_round', 'hard', 'What AKC group is the French Bulldog in?', 'Non-Sporting Group', 'Toy Group', 'Terrier Group', 'Working Group', NULL, NULL, 0, 1),
('speed_round', 'hard', 'What FCI group number is the French Bulldog in?', 'Group 9', 'Group 2', 'Group 3', 'Group 1', NULL, NULL, 0, 1),
('speed_round', 'hard', 'What gene causes the blue dilution?', 'D locus (d/d)', 'B locus', 'E locus', 'K locus', NULL, NULL, 0, 1),
('speed_round', 'hard', 'What year was the FBDCA founded?', '1897', '1898', '1900', '1885', NULL, NULL, 0, 1),
('speed_round', 'hard', 'What condition is abbreviated BOAS?', 'Brachycephalic Obstructive Airway Syndrome', 'Bulldog Obstruction Asthma Syndrome', NULL, NULL, NULL, NULL, 0, 1),

-- ============================================================
-- CATEGORY 14: EXPERT ONLY (33 questions)
-- ============================================================

('expert_only', 'hard', 'What is the genetic test panel offered by UC Davis VGL for French Bulldogs?', 'French Bulldog Health Panel', 'Canine Complete Screen', 'Bulldog DNA Profile', 'Brachycephalic Gene Test', 'UC Davis VGL offers a French Bulldog Health Panel testing for conditions including DM, CMR1, HUU, JHC, and others.', NULL, 0, 1),
('expert_only', 'hard', 'What condition abbreviated HUU causes French Bulldogs to form uric acid bladder stones?', 'Hyperuricosuria', 'Hyperthyroidism', 'Hemolytic Uremic Syndrome', 'Hypertrophic Urethropathy', 'HUU is an inherited condition where affected dogs excrete excessive uric acid in urine, leading to urate bladder stones.', NULL, 0, 1),
('expert_only', 'hard', 'In the FCI classification, what group are French Bulldogs placed in?', 'Group 9: Companion and Toy Dogs', 'Group 2: Pinscher and Schnauzer type', 'Group 3: Terriers', 'Group 1: Sheepdogs and Cattledogs', 'The FCI classifies French Bulldogs in Group 9, Section 11 (Small Molossian Dogs).', NULL, 0, 1),
('expert_only', 'hard', 'What AKC group does the French Bulldog belong to?', 'Non-Sporting Group', 'Toy Group', 'Terrier Group', 'Working Group', 'Despite their small size, French Bulldogs are classified in the AKC Non-Sporting Group, not the Toy Group.', NULL, 0, 1),
('expert_only', 'hard', 'What hereditary condition called CMR1 affects the retina in French Bulldogs?', 'Canine Multifocal Retinopathy 1', 'Canine Macular Regression 1', 'Chronic Myopic Retinitis', 'Central Membrane Rupture 1', 'CMR1 is an inherited eye condition that causes raised lesions on the retina. It is tested for in the French Bulldog Health Panel.', NULL, 0, 1),
('expert_only', 'hard', 'What does OFA stand for in canine health testing?', 'Orthopedic Foundation for Animals', 'Official Foundation for Animal health', 'Organization of Functional Assessment', 'Orthopaedic Fitness Authority', 'The OFA maintains a registry of health test results and provides certification for breeding dogs, including hip, patella, and BOAS evaluations.', NULL, 0, 1),
('expert_only', 'hard', 'What is the term for a French Bulldog with the chondrodystrophic body type?', 'CDDY/CDPA — chondrodystrophy and chondrodysplasia', 'Short-legged phenotype', 'Achondroplasia Type 1', 'Dwarfism gene carrier', 'French Bulldogs carry genes for chondrodystrophy (CDDY) and chondrodysplasia (CDPA) which cause their short-legged, stocky body type and increase IVDD risk.', NULL, 0, 1),
('expert_only', 'hard', 'What does "coefficient of inbreeding" (COI) measure in breeding?', 'The probability that two genes are identical by descent from a common ancestor', 'The number of inbred generations', 'The total number of ancestors', 'The ratio of males to females in a pedigree', 'COI measures genetic diversity. Higher COI means more inbreeding. The French Bulldog breed has a relatively high average COI due to its small founding population.', NULL, 0, 1),
('expert_only', 'hard', 'What is the FBDCA''s position on breeding merle French Bulldogs?', 'Strongly opposed — merle is a disqualifying colour and raises health concerns', 'Fully supportive of merle breeding', 'Neutral — breeders can choose', 'They only oppose double merle breeding', 'The FBDCA opposes merle breeding, noting it is a disqualifying colour and that merle-to-merle breeding causes severe health defects.', NULL, 0, 1),
('expert_only', 'hard', 'What is Degenerative Myelopathy (DM) and why is it tested for in Frenchies?', 'A progressive spinal cord disease causing hind leg weakness and paralysis', 'A dental disease causing tooth loss', 'A skin condition causing hair loss', 'A liver disease causing jaundice', 'DM is a progressive neurological disease. DNA testing identifies carriers so breeders can avoid producing affected puppies.', NULL, 0, 1),
('expert_only', 'hard', 'What imaging technique provides the best evaluation of IVDD in French Bulldogs?', 'MRI combined with CT scan', 'Standard X-ray only', 'Ultrasound only', 'Blood tests', 'While X-rays show bone changes, MRI provides detailed imaging of soft tissue including discs and spinal cord, making it the gold standard for IVDD diagnosis.', NULL, 0, 1),
('expert_only', 'hard', 'What is "Juvenile Hereditary Cataracts" (JHC) in French Bulldogs?', 'An inherited form of cataracts that develops at a young age', 'Cataracts that only affect senior dogs', 'Eye clouding from environmental exposure', 'A bacterial eye infection in puppies', 'JHC is a genetic condition tested for in the French Bulldog Health Panel. Affected dogs develop cataracts much earlier than the typical age-related form.', NULL, 0, 1),
('expert_only', 'hard', 'What is "Cystinuria Type 3" and why is it relevant to French Bulldogs?', 'A genetic kidney condition causing cystine stones in the urinary tract', 'A skin condition affecting fur growth', 'A breathing disorder', 'A type of epilepsy', 'Cystinuria Type 3 causes the amino acid cystine to accumulate in urine, forming painful stones. It is one of the conditions tested in breed-specific DNA panels.', NULL, 0, 1),
('expert_only', 'hard', 'What surgical procedure involves widening a French Bulldog''s nostrils?', 'Rhinoplasty or alarplasty for stenotic nares', 'Tracheostomy', 'Stent placement', 'Nasal bridge lift', 'Stenotic nares (narrowed nostrils) can be surgically widened to improve airflow. This is one of the most common BOAS-corrective surgeries.', NULL, 0, 1),
('expert_only', 'hard', 'What does "staphylectomy" involve in BOAS surgery?', 'Shortening the elongated soft palate', 'Removing the tonsils', 'Widening the nostrils', 'Inserting a tracheal stent', 'An elongated soft palate partially blocks the airway. Staphylectomy trims it to an appropriate length, significantly improving breathing.', NULL, 0, 1),
('expert_only', 'hard', 'What is PennHIP and how does it differ from OFA hip evaluation?', 'A stress-radiograph method measuring joint laxity vs OFA''s subjective scoring', 'A blood test for hip disease', 'A physical exam technique', 'An MRI-based assessment', 'PennHIP uses distraction radiographs to quantitatively measure hip joint laxity, while OFA uses standard radiographs graded subjectively by veterinary radiologists.', NULL, 0, 1),
('expert_only', 'hard', 'What does RFG stand for in French Bulldog health assessment?', 'Respiratory Function Grading', 'Registered Frenchie Grade', 'Radiology Function Guide', 'Renal Filtration Grade', 'Respiratory Function Grading is a standardised assessment of breathing function in brachycephalic breeds, administered through the OFA.', NULL, 0, 1),
('expert_only', 'hard', 'What FCI section specifically classifies the French Bulldog within Group 9?', 'Section 11: Small Molossian Dogs', 'Section 1: Bichons', 'Section 5: Tibetan Breeds', 'Section 9: Continental Toy Spaniels', 'The FCI places the French Bulldog specifically in Group 9, Section 11 (Small Molossian Dogs), distinguishing them from toy breeds.', NULL, 0, 1);
