-- ============================================================
-- Frenchie Trivia — Batch 2 (~252 additional questions)
-- Append to questions_500.sql for full 500-question bank
-- ============================================================

INSERT INTO questions (category, difficulty, question, correct_answer, incorrect_answer_1, incorrect_answer_2, incorrect_answer_3, explanation, fun_fact, is_premium, is_active) VALUES

-- ============================================================
-- BREED HISTORY — 7 more (29→36)
-- ============================================================
('breed_history', 'easy', 'What river did the lace workers cross to bring toy bulldogs from England to France?', 'The English Channel', 'The River Thames', 'The River Seine', 'The Rhine', 'Nottingham lace workers crossed the English Channel to settle in the Normandy area of northern France.', NULL, 0, 1),
('breed_history', 'medium', 'What Paris neighbourhood was most associated with French Bulldogs in the late 1800s?', 'Montmartre', 'Le Marais', 'Saint-Germain-des-Prés', 'Champs-Élysées', 'Montmartre, the bohemian artists'' quarter, was closely associated with French Bulldogs and their fashionable owners.', NULL, 0, 1),
('breed_history', 'medium', 'What weight range did the original Toy Bulldogs fall into?', '12 to 25 pounds', '5 to 10 pounds', '30 to 40 pounds', '40 to 50 pounds', 'The Toy Bulldogs that became French Bulldogs weighed approximately 12-25 pounds with either upright or rose ears.', NULL, 0, 1),
('breed_history', 'medium', 'What region of France did displaced English lace workers primarily settle in?', 'Normandy', 'Provence', 'Brittany', 'Bordeaux', 'The lace makers settled in Normandy in northern France, where their skills with fabric and needle were still valued.', NULL, 0, 1),
('breed_history', 'hard', 'What year were classes for French Bulldogs first included in a Westminster catalogue?', '1897', '1890', '1900', '1905', 'A French Bulldog appeared on the cover of the 1897 Westminster catalogue even before the breed was officially AKC-approved.', NULL, 0, 1),
('breed_history', 'hard', 'What was the controversy at the 1897 Westminster show that angered American Frenchie fanciers?', 'The English judge only awarded prizes to rose-eared dogs, not bat-eared', 'Dogs were too large', 'Only brindle dogs were shown', 'The show was cancelled', 'Judge George Raper only chose rose-eared winners, infuriating American fans who preferred bat ears, leading them to form the FBDCA.', NULL, 0, 1),
('breed_history', 'hard', 'In what year did the English Kennel Club change French Bulldogs'' name from Bouledogue Français to French Bulldog?', '1912', '1905', '1898', '1920', 'The Kennel Club first recognised them as Bouledogue Français in 1905, then changed the name to French Bulldog in 1912.', NULL, 0, 1),

-- ============================================================
-- HEALTH & WELLNESS — 12 more (24→36)
-- ============================================================
('health_wellness', 'easy', 'What should you clean regularly on a French Bulldog to prevent infections?', 'Their facial wrinkles and skin folds', 'Their tail only', 'Their teeth only', 'Their eyelashes', 'Moisture and bacteria can get trapped in facial folds, causing irritation and infection if not cleaned and dried regularly.', NULL, 0, 1),
('health_wellness', 'easy', 'What season is most dangerous for French Bulldogs?', 'Summer — heat is a serious threat', 'Winter', 'Spring', 'Autumn', 'French Bulldogs cannot regulate body temperature well. Hot weather can quickly lead to heatstroke and is potentially fatal.', NULL, 0, 1),
('health_wellness', 'medium', 'What ear condition are French Bulldogs prone to because of their narrow ear canals?', 'Chronic ear infections (otitis)', 'Torn eardrums', 'Ear mites only', 'Hearing loss from loud noise', 'Frenchies have narrow ear canals that trap moisture and debris, creating an environment for chronic bacterial and yeast infections.', NULL, 0, 1),
('health_wellness', 'medium', 'What is the most important weight management strategy for French Bulldogs?', 'Careful portion control and measured feeding', 'Skipping meals twice a week', 'Extreme exercise', 'Feeding only vegetables', 'Frenchies gain weight easily. Measuring food portions and monitoring calorie intake from treats is the most effective prevention.', NULL, 0, 1),
('health_wellness', 'medium', 'What dental issue are French Bulldogs prone to due to their jaw structure?', 'Overcrowded teeth that trap food and bacteria', 'Missing all teeth', 'Extra rows of teeth', 'Teeth that grow too long', 'The shortened jaw means teeth are often crowded, making dental disease more likely. Regular dental care is essential.', NULL, 0, 1),
('health_wellness', 'medium', 'What is the recommended frequency for veterinary check-ups for a French Bulldog?', 'At least once per year, more frequently for seniors', 'Only when visibly sick', 'Every 5 years', 'Once in their lifetime', 'Regular wellness visits help catch breed-specific issues early. Senior Frenchies and those with health conditions should visit more frequently.', NULL, 0, 1),
('health_wellness', 'hard', 'What is "Brachycephalic Syndrome" beyond just BOAS?', 'A collection of upper airway abnormalities including elongated palate, stenotic nares, everted laryngeal saccules, and hypoplastic trachea', 'Just narrowed nostrils', 'Only soft palate problems', 'A heart condition', 'Brachycephalic Syndrome encompasses multiple anatomical issues that collectively restrict airflow, each of which can be surgically addressed.', NULL, 0, 1),
('health_wellness', 'hard', 'What autoimmune condition affecting the thyroid is tested for in French Bulldogs?', 'Autoimmune thyroiditis', 'Graves'' disease', 'Hashimoto''s disease', 'Thyroid cancer', 'Autoimmune thyroiditis is on the CHIC testing list for French Bulldogs and can lead to hypothyroidism if untreated.', NULL, 0, 1),
('health_wellness', 'hard', 'What joint condition involves abnormal development of the elbow joint?', 'Elbow dysplasia', 'Tennis elbow', 'Elbow bursitis', 'Elbow dislocation', 'Elbow dysplasia is included on the CHIC testing list for Frenchies and involves abnormal development of the elbow joint components.', NULL, 0, 1),
('health_wellness', 'hard', 'What does "everted laryngeal saccules" mean in BOAS-affected dogs?', 'Tissue near the vocal cords gets sucked into the airway due to increased breathing effort', 'The voice box moves forward', 'The larynx becomes paralysed', 'Excess tissue grows over the tongue', 'Chronic airway obstruction causes negative pressure that pulls the laryngeal saccules into the airway, further narrowing it. This is a secondary BOAS complication.', NULL, 0, 1),
('health_wellness', 'hard', 'What percentage of French Bulldogs are estimated to have at least one health issue?', 'Around 72%', 'About 30%', 'Less than 10%', 'Almost 100%', 'Studies suggest approximately 72% of French Bulldogs experience health issues, many related to their brachycephalic anatomy.', NULL, 0, 1),
('health_wellness', 'medium', 'What type of harness is recommended for French Bulldogs instead of a collar?', 'A well-fitted body harness that doesn''t put pressure on the neck', 'A head halter', 'A choke chain', 'A standard flat collar is fine', 'Harnesses distribute pressure across the chest rather than the neck, protecting the already-compromised Frenchie airway.', NULL, 0, 1),

-- ============================================================
-- GENETICS & COLOURS — 13 more (23→36)
-- ============================================================
('genetics_colours', 'easy', 'What is the most common fawn shade seen in French Bulldogs?', 'A warm tan/golden colour', 'Pure white', 'Bright orange', 'Black', 'Fawn ranges from light cream-tan to deep reddish-brown, with a warm golden shade being the most common.', NULL, 0, 1),
('genetics_colours', 'easy', 'Do all fawn French Bulldogs have a black mask?', 'No — some fawn Frenchies are maskless', 'Yes, all fawn dogs have masks', 'Only males have masks', 'Only puppies have masks', 'While many fawn Frenchies sport a black mask (controlled by the Em gene), some are maskless. Both variations are accepted by the AKC.', NULL, 0, 1),
('genetics_colours', 'medium', 'What is a "trindle" French Bulldog?', 'A tricolour dog with brindle in the tan-point areas', 'A triple merle dog', 'A ticked brindle', 'A tri-colour pied', 'Trindle refers to brindle stripes appearing within the lighter tan-point markings on a tricolour dog.', NULL, 0, 1),
('genetics_colours', 'medium', 'What is a "platinum" French Bulldog?', 'A cream-coated dog carrying three recessive dilution gene pairs', 'A silver-coloured Frenchie', 'A pure white albino', 'A light blue Frenchie', 'Platinum Frenchies appear cream or white but carry multiple recessive dilution genes, giving their coat extra shine and lighter pigmentation around the face.', NULL, 0, 1),
('genetics_colours', 'medium', 'How does the cream gene (e/e) affect a dog that also carries the mask gene?', 'The cream gene deletes/erases the mask completely', 'The mask becomes lighter', 'The mask turns brown', 'There is no effect', 'Two copies of the cream gene (e/e) prevent production of dark pigment in the coat, which erases any mask the dog genetically carries.', NULL, 0, 1),
('genetics_colours', 'medium', 'Is brindle a dominant or recessive gene in French Bulldogs?', 'Brindle is dominant — only one copy is needed to express',